import type { InitialDisplacement, Preset } from "../types/scenario";
import { buildModelProvenance, provenanceSummary, type ModelProvenanceInput } from "./model-provenance";
import type { RunupAtPointResult } from "./tauri";

export type TextExportData = ModelProvenanceInput & {
  preset?: Preset | null;
  initial?: InitialDisplacement | null;
  timeS: number;
  runupResults?: RunupAtPointResult[];
};

export function generateTextExport(data: TextExportData): string {
  const lines: string[] = [];
  lines.push("TsunamiSimulator — Scenario Results Export");
  lines.push("==========================================");
  lines.push("");

  const provenance = buildModelProvenance(data);
  lines.push("Provenance");
  lines.push("----------");
  lines.push(provenanceSummary({ ...data, generatedAt: provenance.generatedAt }));
  lines.push("");

  if (data.preset) {
    lines.push(`Preset: ${data.preset.name}`);
    lines.push(`Date: ${data.preset.date}`);
    lines.push(`Reference: ${data.preset.reference}`);
    if (data.preset.is_speculative) {
      lines.push("Note: This is a speculative/controversial scenario.");
      if (data.preset.controversy_note) {
        lines.push(`  ${data.preset.controversy_note}`);
      }
    }
    lines.push("");
  }

  if (data.initial) {
    const i = data.initial;
    lines.push("Source Parameters");
    lines.push("-----------------");
    lines.push(`Label: ${i.label}`);
    const ns = i.center.lat_deg >= 0 ? "N" : "S";
    const ew = i.center.lon_deg >= 0 ? "E" : "W";
    lines.push(`Location: ${Math.abs(i.center.lat_deg).toFixed(4)}° ${ns}, ${Math.abs(i.center.lon_deg).toFixed(4)}° ${ew}`);
    if (i.center.depth_m !== undefined) {
      lines.push(`Water depth: ${i.center.depth_m.toFixed(0)} m`);
    }
    lines.push(`Peak amplitude: ${i.peak_amplitude_m.toFixed(2)} m`);
    lines.push(`Cavity radius: ${i.cavity_radius_m.toFixed(0)} m`);
    lines.push(`Source energy: ${formatEnergy(i.source_energy_j)}`);
    lines.push(`Seismic equivalent: Mw ${i.seismic_mw_equivalent.toFixed(1)}`);
    if (i.dominant_wavelength_m) {
      lines.push(`Dominant wavelength: ${(i.dominant_wavelength_m / 1000).toFixed(1)} km`);
    }
    lines.push("");
  }

  lines.push(`Simulation time: ${(data.timeS / 60).toFixed(0)} minutes`);
  lines.push("");

  if (data.runupResults && data.runupResults.length > 0) {
    lines.push("Coastal Runup Results");
    lines.push("---------------------");
    lines.push(
      padRow(["Location", "Lat", "Lon", "Runup (m)", "Offshore (m)", "Arrival", "Status"]),
    );
    lines.push("-".repeat(100));

    const sorted = [...data.runupResults].sort((a, b) => b.runup_m - a.runup_m);
    for (const r of sorted) {
      const arrivalMin = r.arrival_time_s / 60;
      const arrival = !Number.isFinite(arrivalMin)
        ? "—"
        : arrivalMin < 60
          ? `T+${arrivalMin.toFixed(0)}m`
          : `T+${Math.floor(arrivalMin / 60)}h${String(Math.round(arrivalMin % 60)).padStart(2, "0")}`;
      lines.push(
        padRow([
          r.name,
          r.lat.toFixed(2),
          r.lon.toFixed(2),
          r.has_arrived ? r.runup_m.toFixed(2) : "—",
          Number.isFinite(r.offshore_amplitude_m) ? r.offshore_amplitude_m.toFixed(3) : "—",
          arrival,
          r.has_arrived ? "Arrived" : "In transit",
        ]),
      );
    }
    lines.push("");
  }

  lines.push("---");
  lines.push("Educational only — not for evacuation planning.");
  lines.push("Generated by TsunamiSimulator (github.com/SysAdminDoc/TsunamiSimulator)");

  return lines.join("\n");
}

function formatEnergy(j: number): string {
  if (!Number.isFinite(j)) return "—";
  const mt = j / 4.184e15;
  if (mt >= 1) return `${mt.toFixed(1)} Mt TNT (${j.toExponential(2)} J)`;
  if (mt >= 1e-3) return `${(mt * 1000).toFixed(1)} kt TNT (${j.toExponential(2)} J)`;
  return `${j.toExponential(2)} J`;
}

function padRow(cols: string[]): string {
  const widths = [24, 8, 8, 10, 14, 10, 10];
  return cols.map((c, i) => c.padEnd(widths[i] ?? 10)).join("  ");
}

export function downloadTextExport(data: TextExportData): void {
  const text = generateTextExport(data);
  const blob = new Blob([text], { type: "text/plain;charset=utf-8" });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  const presetId = data.preset?.id ?? "custom-scenario";
  a.download = `tsunamisim-${presetId}-results.txt`;
  document.body.appendChild(a);
  a.click();
  a.remove();
  setTimeout(() => URL.revokeObjectURL(url), 5_000);
}
