use super::*;
use netcdf3::{DataSet, FileWriter, NC_FILL_F32, Version};
use sha2::{Digest, Sha256};
use std::fs;

const SCIENTIFIC_EXPORT_DIR: &str = "scientific-exports";
const SCIENTIFIC_EXPORT_MAX_CELLS: usize = 1_000_000;
const SCIENTIFIC_EXPORT_MAX_BYTES: u64 = 96 * 1024 * 1024;
const SCIENTIFIC_EXPORT_RETAINED_FILES: usize = 4;

#[derive(Debug, Clone, Serialize)]
pub struct ScientificExportDescriptor {
    pub export_id: String,
    pub suggested_filename: String,
    pub bytes: u64,
    pub format: &'static str,
    pub conventions: &'static str,
}

fn export_root(app_data_dir: &Path) -> PathBuf {
    app_data_dir.join(SCIENTIFIC_EXPORT_DIR)
}

fn validate_export_shape(grid: &SwGrid) -> Result<usize, String> {
    let cells = grid
        .nx
        .checked_mul(grid.ny)
        .ok_or_else(|| "scientific export grid dimensions overflow".to_string())?;
    if grid.nx < 2 || grid.ny < 2 || cells > SCIENTIFIC_EXPORT_MAX_CELLS {
        return Err(format!(
            "scientific export rejected: {}x{} grid has {cells} cells; NetCDF export is limited to {SCIENTIFIC_EXPORT_MAX_CELLS} cells",
            grid.nx, grid.ny
        ));
    }
    let fields = [&grid.h_m, &grid.eta_m, &grid.u_ms, &grid.v_ms];
    if fields.iter().any(|field| field.len() != cells) {
        return Err(
            "scientific export rejected: solver field shape does not match the grid".into(),
        );
    }
    if fields
        .iter()
        .flat_map(|field| field.iter())
        .any(|value| !value.is_finite())
        || !grid.t_s.is_finite()
    {
        return Err("scientific export rejected: solver fields contain a non-finite value".into());
    }
    Ok(cells)
}

fn add_text_attr(
    data_set: &mut DataSet,
    variable: &str,
    name: &str,
    value: &str,
) -> Result<(), String> {
    data_set
        .get_var_mut(variable)
        .ok_or_else(|| format!("NetCDF variable '{variable}' is unavailable"))?
        .add_attr_string(name, value)
        .map_err(|error| format!("failed to add NetCDF attribute {variable}:{name}: {error}"))
}

fn add_field(
    data_set: &mut DataSet,
    name: &str,
    dimensions: &[&str],
    long_name: &str,
    units: &str,
    standard_name: Option<&str>,
) -> Result<(), String> {
    data_set
        .add_var_f32(name, dimensions)
        .map_err(|error| format!("failed to define NetCDF variable '{name}': {error}"))?;
    add_text_attr(data_set, name, "long_name", long_name)?;
    add_text_attr(data_set, name, "units", units)?;
    if let Some(standard_name) = standard_name {
        add_text_attr(data_set, name, "standard_name", standard_name)?;
    }
    add_text_attr(data_set, name, "grid_mapping", "crs")?;
    Ok(())
}

fn f32_field(values: &[f64]) -> Vec<f32> {
    values.iter().map(|value| *value as f32).collect()
}

fn write_scientific_netcdf(
    path: &Path,
    run_id: &str,
    req: &SimulateGridRequest,
    grid: &SwGrid,
    max_field: &MaxFieldAccumulator,
    run_quality: &RunQualityRecord,
    used_gpu: bool,
) -> Result<(), String> {
    let cells = validate_export_shape(grid)?;
    let [peak_m, t_of_max_s, arrival_s, energy_m2s] = max_field.scientific_fields();
    if [peak_m, t_of_max_s, arrival_s, energy_m2s]
        .iter()
        .any(|field| field.len() != cells)
    {
        return Err("scientific export rejected: max-field shape does not match the grid".into());
    }

    let canonical_request = serde_json::to_vec(req)
        .map_err(|error| format!("failed to serialize scientific-export provenance: {error}"))?;
    let scenario_sha256 = crate::render_protocol::sha256_hex(&canonical_request);
    let scenario_json = String::from_utf8(canonical_request)
        .map_err(|error| format!("failed to encode scientific-export provenance: {error}"))?;
    let quality_json = serde_json::to_string(run_quality)
        .map_err(|error| format!("failed to serialize scientific-export quality: {error}"))?;
    let source = format!(
        "Cataclysm {} finite-volume shallow-water solver",
        env!("CARGO_PKG_VERSION")
    );
    let history = format!("Generated by Cataclysm {}", env!("CARGO_PKG_VERSION"));
    let bathymetry_source = if req.use_real_bathymetry {
        if req.bathymetry_asset_id.is_some() {
            "validated user-supplied scientific raster"
        } else {
            "bundled coarse basin/shelf bathymetry"
        }
    } else {
        "uniform analytical depth from the scenario request"
    };

    let mut data_set = DataSet::new();
    for (name, value) in [
        ("Conventions", "CF-1.12"),
        ("title", "Cataclysm shallow-water solver products"),
        ("institution", "SysAdminDoc / Cataclysm Project"),
        ("source", &source),
        ("history", &history),
        (
            "references",
            "LeVeque et al. (2011), doi:10.1029/2011GL049210; Synolakis (1987), doi:10.1017/S002211208700175X; https://github.com/SysAdminDoc/Cataclysm",
        ),
        (
            "comment",
            "Final solver state and solver-step max-field products. Longitude remains monotonically unwrapped across the antimeridian when required.",
        ),
        ("cataclysm_run_id", run_id),
        ("cataclysm_scenario_sha256", &scenario_sha256),
        ("cataclysm_scenario_json", &scenario_json),
        ("cataclysm_bathymetry_source", bathymetry_source),
        (
            "cataclysm_solver_backend",
            if used_gpu {
                "wgpu with CPU fallback"
            } else {
                "CPU rayon"
            },
        ),
        (
            "cataclysm_horizontal_crs",
            "WGS 84 geographic coordinates (EPSG:4326)",
        ),
        (
            "cataclysm_vertical_datum",
            "mean sea level; modeled sea-surface displacement",
        ),
        ("cataclysm_quality_record", &quality_json),
    ] {
        data_set
            .add_global_attr_string(name, value)
            .map_err(|error| format!("failed to add NetCDF global attribute '{name}': {error}"))?;
    }
    if let Some(asset_id) = req.bathymetry_asset_id.as_deref() {
        data_set
            .add_global_attr_string("cataclysm_bathymetry_asset_id", asset_id)
            .map_err(|error| format!("failed to add NetCDF bathymetry provenance: {error}"))?;
    }

    data_set
        .add_fixed_dim("time", 1)
        .map_err(|error| format!("failed to define NetCDF time dimension: {error}"))?;
    data_set
        .add_fixed_dim("latitude", grid.ny)
        .map_err(|error| format!("failed to define NetCDF latitude dimension: {error}"))?;
    data_set
        .add_fixed_dim("longitude", grid.nx)
        .map_err(|error| format!("failed to define NetCDF longitude dimension: {error}"))?;

    data_set
        .add_var_f64("time", &["time"])
        .map_err(|error| format!("failed to define NetCDF time coordinate: {error}"))?;
    for (name, value) in [
        ("standard_name", "time"),
        ("long_name", "simulation time"),
        ("units", "seconds since 1970-01-01 00:00:00 UTC"),
        ("calendar", "proleptic_gregorian"),
        ("axis", "T"),
        (
            "comment",
            "Relative simulation time; the epoch is a conventional coordinate origin, not the hazard event date.",
        ),
    ] {
        add_text_attr(&mut data_set, "time", name, value)?;
    }

    for (name, size, standard_name, units, axis, long_name) in [
        (
            "latitude",
            grid.ny,
            "latitude",
            "degrees_north",
            "Y",
            "cell-center latitude",
        ),
        (
            "longitude",
            grid.nx,
            "longitude",
            "degrees_east",
            "X",
            "cell-center longitude",
        ),
    ] {
        let _ = size;
        data_set
            .add_var_f64(name, &[name])
            .map_err(|error| format!("failed to define NetCDF {name} coordinate: {error}"))?;
        add_text_attr(&mut data_set, name, "standard_name", standard_name)?;
        add_text_attr(&mut data_set, name, "long_name", long_name)?;
        add_text_attr(&mut data_set, name, "units", units)?;
        add_text_attr(&mut data_set, name, "axis", axis)?;
    }

    data_set
        .add_var_i32::<&str>("crs", &[])
        .map_err(|error| format!("failed to define NetCDF CRS variable: {error}"))?;
    add_text_attr(
        &mut data_set,
        "crs",
        "grid_mapping_name",
        "latitude_longitude",
    )?;
    {
        let crs = data_set
            .get_var_mut("crs")
            .ok_or_else(|| "NetCDF CRS variable is unavailable".to_string())?;
        crs.add_attr_f64("semi_major_axis", vec![6_378_137.0])
            .map_err(|error| format!("failed to add NetCDF CRS semi-major axis: {error}"))?;
        crs.add_attr_f64("inverse_flattening", vec![298.257_223_563])
            .map_err(|error| format!("failed to add NetCDF CRS inverse flattening: {error}"))?;
        crs.add_attr_f64("longitude_of_prime_meridian", vec![0.0])
            .map_err(|error| format!("failed to add NetCDF CRS prime meridian: {error}"))?;
    }

    let state_dims = &["time", "latitude", "longitude"];
    let grid_dims = &["latitude", "longitude"];
    add_field(
        &mut data_set,
        "sea_surface_height",
        state_dims,
        "final sea-surface displacement",
        "m",
        Some("sea_surface_height_above_sea_level"),
    )?;
    add_text_attr(&mut data_set, "sea_surface_height", "positive", "up")?;
    add_field(
        &mut data_set,
        "eastward_sea_water_velocity",
        state_dims,
        "final eastward depth-averaged sea-water velocity",
        "m s-1",
        Some("eastward_sea_water_velocity"),
    )?;
    add_field(
        &mut data_set,
        "northward_sea_water_velocity",
        state_dims,
        "final northward depth-averaged sea-water velocity",
        "m s-1",
        Some("northward_sea_water_velocity"),
    )?;
    add_field(
        &mut data_set,
        "sea_floor_depth",
        grid_dims,
        "sea-floor depth below mean sea level",
        "m",
        Some("sea_floor_depth_below_mean_sea_level"),
    )?;
    add_text_attr(&mut data_set, "sea_floor_depth", "positive", "down")?;
    add_field(
        &mut data_set,
        "maximum_absolute_sea_surface_height",
        grid_dims,
        "maximum absolute sea-surface displacement",
        "m",
        None,
    )?;
    add_text_attr(
        &mut data_set,
        "maximum_absolute_sea_surface_height",
        "cell_methods",
        "time: maximum",
    )?;
    add_text_attr(
        &mut data_set,
        "maximum_absolute_sea_surface_height",
        "coordinates",
        "time",
    )?;
    add_field(
        &mut data_set,
        "time_of_maximum_sea_surface_height",
        grid_dims,
        "time of maximum absolute sea-surface displacement",
        "s",
        None,
    )?;
    add_field(
        &mut data_set,
        "first_arrival_time",
        grid_dims,
        "first threshold-crossing arrival time",
        "s",
        None,
    )?;
    add_text_attr(
        &mut data_set,
        "first_arrival_time",
        "comment",
        "Threshold is max(1 cm, 1 percent of source amplitude); missing values indicate no threshold crossing.",
    )?;
    data_set
        .get_var_mut("first_arrival_time")
        .ok_or_else(|| "NetCDF arrival variable is unavailable".to_string())?
        .add_attr_f32("_FillValue", vec![NC_FILL_F32])
        .map_err(|error| format!("failed to add NetCDF arrival fill value: {error}"))?;
    add_field(
        &mut data_set,
        "time_integrated_squared_sea_surface_height",
        grid_dims,
        "time integral of squared sea-surface displacement",
        "m2 s",
        None,
    )?;

    let mut writer = FileWriter::open(path)
        .map_err(|error| format!("failed to create NetCDF export: {error:?}"))?;
    writer
        .set_def(&data_set, Version::Classic, 0)
        .map_err(|error| format!("failed to write NetCDF schema: {error:?}"))?;
    writer
        .write_var_f64("time", &[grid.t_s])
        .map_err(|error| format!("failed to write NetCDF time: {error:?}"))?;
    let latitudes: Vec<f64> = (0..grid.ny)
        .map(|j| grid.south_lat + (j as f64 + 0.5) * grid.dlat_deg)
        .collect();
    let longitudes: Vec<f64> = (0..grid.nx)
        .map(|i| grid.west_lon + (i as f64 + 0.5) * grid.dlon_deg)
        .collect();
    writer
        .write_var_f64("latitude", &latitudes)
        .map_err(|error| format!("failed to write NetCDF latitudes: {error:?}"))?;
    writer
        .write_var_f64("longitude", &longitudes)
        .map_err(|error| format!("failed to write NetCDF longitudes: {error:?}"))?;
    writer
        .write_var_i32("crs", &[0])
        .map_err(|error| format!("failed to write NetCDF CRS: {error:?}"))?;

    for (name, values) in [
        ("sea_surface_height", grid.eta_m.as_slice()),
        ("eastward_sea_water_velocity", grid.u_ms.as_slice()),
        ("northward_sea_water_velocity", grid.v_ms.as_slice()),
        ("sea_floor_depth", grid.h_m.as_slice()),
        ("maximum_absolute_sea_surface_height", peak_m),
        ("time_of_maximum_sea_surface_height", t_of_max_s),
        ("time_integrated_squared_sea_surface_height", energy_m2s),
    ] {
        writer
            .write_var_f32(name, &f32_field(values))
            .map_err(|error| format!("failed to write NetCDF variable '{name}': {error:?}"))?;
    }
    let arrival: Vec<f32> = arrival_s
        .iter()
        .map(|value| {
            if value.is_finite() {
                *value as f32
            } else {
                NC_FILL_F32
            }
        })
        .collect();
    writer
        .write_var_f32("first_arrival_time", &arrival)
        .map_err(|error| format!("failed to write NetCDF arrival times: {error:?}"))?;
    writer
        .close()
        .map_err(|error| format!("failed to finalize NetCDF export: {error:?}"))
}

fn prune_export_cache(root: &Path) {
    let Ok(entries) = fs::read_dir(root) else {
        return;
    };
    let mut files: Vec<_> = entries
        .flatten()
        .filter_map(|entry| {
            let path = entry.path();
            (path.extension().and_then(|ext| ext.to_str()) == Some("nc"))
                .then(|| (entry.metadata().and_then(|meta| meta.modified()).ok(), path))
        })
        .collect();
    files.sort_by_key(|entry| std::cmp::Reverse(entry.0));
    for (_, path) in files.into_iter().skip(SCIENTIFIC_EXPORT_RETAINED_FILES) {
        let _ = fs::remove_file(path);
    }
}

pub(crate) fn create_cached_scientific_export(
    app_data_dir: &Path,
    run_id: &str,
    req: &SimulateGridRequest,
    grid: &SwGrid,
    max_field: &MaxFieldAccumulator,
    run_quality: &RunQualityRecord,
    used_gpu: bool,
) -> Result<ScientificExportDescriptor, String> {
    validate_export_shape(grid)?;
    let root = export_root(app_data_dir);
    fs::create_dir_all(&root)
        .map_err(|error| format!("failed to create scientific-export cache: {error}"))?;
    let mut hash = Sha256::new();
    hash.update(run_id.as_bytes());
    hash.update(grid.step_index.to_le_bytes());
    hash.update(
        serde_json::to_vec(req)
            .map_err(|error| format!("failed to identify scientific export: {error}"))?,
    );
    let export_id = format!("{:x}", hash.finalize())[..32].to_string();
    let path = root.join(format!("{export_id}.nc"));
    let temporary = root.join(format!(".{export_id}.tmp"));
    if temporary.exists() {
        let _ = fs::remove_file(&temporary);
    }
    if let Err(error) = write_scientific_netcdf(
        &temporary,
        run_id,
        req,
        grid,
        max_field,
        run_quality,
        used_gpu,
    ) {
        let _ = fs::remove_file(&temporary);
        return Err(error);
    }
    fs::rename(&temporary, &path)
        .map_err(|error| format!("failed to publish scientific export: {error}"))?;
    let bytes = fs::metadata(&path)
        .map_err(|error| format!("failed to inspect scientific export: {error}"))?
        .len();
    if bytes == 0 || bytes > SCIENTIFIC_EXPORT_MAX_BYTES {
        let _ = fs::remove_file(&path);
        return Err(format!(
            "scientific export rejected: artifact size {bytes} bytes is outside the supported range"
        ));
    }
    prune_export_cache(&root);
    Ok(ScientificExportDescriptor {
        export_id,
        suggested_filename: format!("cataclysm-{run_id}.nc"),
        bytes,
        format: "NetCDF-3 Classic",
        conventions: "CF-1.12",
    })
}

fn validate_export_id(export_id: &str) -> Result<(), String> {
    if export_id.len() != 32 || !export_id.bytes().all(|byte| byte.is_ascii_hexdigit()) {
        return Err("scientific export id must be exactly 32 hexadecimal characters".into());
    }
    Ok(())
}

fn validate_export_destination(destination: &Path) -> Result<(), String> {
    if !destination.is_absolute() {
        return Err("scientific export destination must be an absolute path".into());
    }
    if destination
        .extension()
        .and_then(|ext| ext.to_str())
        .map(|ext| ext.eq_ignore_ascii_case("nc"))
        != Some(true)
    {
        return Err("scientific export destination must use the .nc extension".into());
    }
    let filename = destination
        .file_name()
        .and_then(|name| name.to_str())
        .ok_or_else(|| "scientific export destination must have a valid filename".to_string())?;
    if filename.len() > 240 {
        return Err("scientific export filename is too long".into());
    }
    let parent = destination
        .parent()
        .ok_or_else(|| "scientific export destination has no parent directory".to_string())?;
    if !parent.is_dir() {
        return Err("scientific export destination directory does not exist".into());
    }
    Ok(())
}

#[tauri::command]
pub fn save_scientific_export(
    app: AppHandle,
    export_id: String,
    destination: String,
) -> Result<u64, String> {
    validate_export_id(&export_id)?;
    let destination = PathBuf::from(destination);
    validate_export_destination(&destination)?;
    let app_data_dir = app
        .path()
        .app_data_dir()
        .map_err(|error| format!("application data directory is unavailable: {error}"))?;
    let source = export_root(&app_data_dir).join(format!("{export_id}.nc"));
    let metadata = fs::metadata(&source)
        .map_err(|_| "scientific export is no longer available; rerun the solver".to_string())?;
    if !metadata.is_file() || metadata.len() == 0 || metadata.len() > SCIENTIFIC_EXPORT_MAX_BYTES {
        return Err("scientific export cache artifact is invalid".into());
    }
    fs::copy(&source, &destination)
        .map_err(|error| format!("failed to save scientific export: {error}"))
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::physics::solver::quality::{RunQualityRecord, RunQualityStatus};
    use tempfile::tempdir;

    fn quality() -> RunQualityRecord {
        RunQualityRecord {
            status: RunQualityStatus::Pass,
            finite_fields: true,
            minimum_total_depth_m: 1000.0,
            cfl_number: 0.4,
            cfl_margin: 0.6,
            accepted_steps: 1,
            rejected_steps: 0,
            mass_drift_pct: 0.0,
            energy_drift_pct: -1.0,
            sponge_width_cells: 1,
            warnings: vec![],
            failure: None,
        }
    }

    fn request() -> SimulateGridRequest {
        serde_json::from_value(serde_json::json!({
            "source": { "lat_deg": 0.0, "lon_deg": 0.0 },
            "initial_amplitude_m": 1.0,
            "source_sigma_m": 1000.0,
            "mean_depth_m": 1000.0,
            "box_half_size_deg": 1.0,
            "cells_per_deg": 1.0,
            "t_end_s": 10.0,
            "n_snapshots": 2
        }))
        .unwrap()
    }

    #[test]
    fn writer_round_trips_through_pinned_reader() {
        let dir = tempdir().unwrap();
        let path = dir.path().join("products.nc");
        let mut grid = SwGrid::new(170.0, -1.0, 173.0, 1.0, 1.0, 1.0);
        grid.fill_uniform_depth(1000.0);
        grid.eta_m = vec![0.1, -0.2, 0.3, 0.4, -0.5, 0.0];
        grid.u_ms.fill(1.25);
        grid.v_ms.fill(-0.75);
        grid.t_s = 12.5;
        grid.step_index = 1;
        let mut max_field = MaxFieldAccumulator::new(grid.nx * grid.ny, 0.01);
        max_field.observe(&grid);
        write_scientific_netcdf(
            &path,
            "run-1",
            &request(),
            &grid,
            &max_field,
            &quality(),
            false,
        )
        .unwrap();

        let file = netcdf_reader::NcFile::open(&path).unwrap();
        assert_eq!(
            file.global_attribute("Conventions")
                .unwrap()
                .value
                .as_string()
                .unwrap(),
            "CF-1.12"
        );
        assert!(
            file.global_attribute("references")
                .unwrap()
                .value
                .as_string()
                .unwrap()
                .contains("LeVeque")
        );
        assert!(
            file.global_attribute("cataclysm_scenario_json")
                .unwrap()
                .value
                .as_string()
                .unwrap()
                .contains("initial_amplitude_m")
        );
        assert!(
            file.global_attribute("cataclysm_quality_record")
                .unwrap()
                .value
                .as_string()
                .unwrap()
                .contains("\"status\":\"pass\"")
        );
        let dimensions = file.dimensions().unwrap();
        assert!(
            dimensions
                .iter()
                .any(|dim| dim.name == "time" && dim.size == 1)
        );
        assert!(
            dimensions
                .iter()
                .any(|dim| dim.name == "latitude" && dim.size == 2)
        );
        assert!(
            dimensions
                .iter()
                .any(|dim| dim.name == "longitude" && dim.size == 3)
        );
        let eta: ndarray::ArrayD<f32> = file.read_variable("sea_surface_height").unwrap();
        assert_eq!(eta.shape(), &[1, 2, 3]);
        assert!((eta[[0, 1, 1]] + 0.5).abs() < 1.0e-6);
        let arrival: ndarray::ArrayD<f32> = file.read_variable("first_arrival_time").unwrap();
        assert_eq!(arrival[[1, 2]], NC_FILL_F32);
        let lat: ndarray::ArrayD<f64> = file.read_variable("latitude").unwrap();
        let lon: ndarray::ArrayD<f64> = file.read_variable("longitude").unwrap();
        assert_eq!(lat.as_slice().unwrap(), &[-0.5, 0.5]);
        assert_eq!(lon.as_slice().unwrap(), &[170.5, 171.5, 172.5]);
        let mut axes: Vec<_> = file
            .cf_coordinate_axes("")
            .unwrap()
            .iter()
            .map(|axis| (axis.variable.name(), axis.axis_type))
            .collect();
        axes.sort_by_key(|axis| axis.0);
        assert_eq!(
            axes,
            vec![
                ("latitude", netcdf_reader::cf::CfAxisType::Y),
                ("longitude", netcdf_reader::cf::CfAxisType::X),
                ("time", netcdf_reader::cf::CfAxisType::T),
            ]
        );
    }

    #[test]
    fn oversized_and_unsafe_exports_fail_closed() {
        let mut grid = SwGrid::new(0.0, 0.0, 2.0, 2.0, 1.0, 1.0);
        grid.nx = SCIENTIFIC_EXPORT_MAX_CELLS + 1;
        grid.ny = 1;
        assert!(
            validate_export_shape(&grid)
                .unwrap_err()
                .contains("limited")
        );
        assert!(validate_export_id("../escape").is_err());
        assert!(validate_export_destination(Path::new("relative.nc")).is_err());
        assert!(validate_export_destination(Path::new("C:\\temp\\wrong.txt")).is_err());
    }
}
