//! Meteotsunami generation by a translating atmospheric-pressure anomaly.
//!
//! The depth-averaged momentum equations receive the surface-pressure source
//!
//! ```text
//! du/dt = -(1/rho_w) dp_a/dx
//! dv/dt = -(1/rho_w) dp_a/dy
//! ```
//!
//! at every accepted solver step.  The pressure footprint is an oriented 2-D
//! Gaussian whose centre translates along a finite track.  This intentionally
//! models pressure-driven generation only: wind stress, harbor resonance, and
//! the later basin seiche remain outside the source contract.
//!
//! References:
//! - NOAA NOS CO-OPS 079, *Meteotsunamis: State of the Science* (2015).
//! - NOAA/NWS, *Meteotsunami Guidelines and Best Practices* (2020).
//! - Anarde et al. (2020), JGR Oceans, doi:10.1029/2020JC016347.

use serde::{Deserialize, Serialize};

#[cfg(not(feature = "browser-wasm"))]
use super::solver::SwGrid;
use super::{
    GeoPoint, InitialDisplacement,
    constants::{G_EARTH, RHO_SEAWATER},
};

/// A finite, translating atmospheric-pressure disturbance.
#[derive(Debug, Clone, Copy, Serialize, Deserialize)]
pub struct MeteotsunamiSource {
    /// Peak positive pressure anomaly, pascals. Positive pressure depresses
    /// the water surface beneath the footprint.
    pub peak_pressure_pa: f64,
    /// Translation speed of the pressure centre, metres per second.
    pub speed_m_s: f64,
    /// Direction of travel clockwise from true north, degrees.
    pub heading_deg: f64,
    /// One-sigma footprint length parallel to the track, metres.
    pub along_track_sigma_m: f64,
    /// One-sigma footprint width normal to the track, metres.
    pub cross_track_sigma_m: f64,
    /// Distance over which the pressure source remains active, metres.
    pub track_length_m: f64,
    /// Representative water depth used for the source summary and resonance
    /// readout. The numerical solver still uses its own per-cell bathymetry.
    pub water_depth_m: f64,
    /// Pressure-centre position at t=0.
    pub location: GeoPoint,
}

impl MeteotsunamiSource {
    /// Long-wave celerity at the source's representative depth.
    pub fn long_wave_speed_m_s(&self) -> f64 {
        (G_EARTH * self.water_depth_m.max(0.0)).sqrt()
    }

    /// Disturbance speed divided by long-wave celerity. Proudman resonance is
    /// approached as this Froude-like ratio tends to one.
    pub fn proudman_ratio(&self) -> f64 {
        let c = self.long_wave_speed_m_s();
        if c > 0.0 { self.speed_m_s / c } else { 0.0 }
    }

    /// Quasi-static inverted-barometer displacement used only as a source
    /// scale in existing analytical readouts. The SWE run starts flat and is
    /// generated by the time-dependent momentum source.
    pub fn inverted_barometer_amplitude_m(&self) -> f64 {
        self.peak_pressure_pa / (RHO_SEAWATER * G_EARTH)
    }

    pub fn initial_displacement(&self) -> InitialDisplacement {
        let amplitude = self.inverted_barometer_amplitude_m();
        let footprint_area =
            2.0 * std::f64::consts::PI * self.along_track_sigma_m * self.cross_track_sigma_m;
        let source_energy_j = 0.5 * RHO_SEAWATER * G_EARTH * amplitude * amplitude * footprint_area;
        InitialDisplacement {
            center: self.location,
            cavity_radius_m: self.along_track_sigma_m.max(self.cross_track_sigma_m),
            // A meteotsunami has no displaced-water IC. This value is the
            // forcing scale consumed by generic UI and threshold readouts.
            peak_amplitude_m: amplitude,
            source_energy_j,
            seismic_mw_equivalent: super::mw_from_radiated_j(source_energy_j),
            dominant_wavelength_m: Some(2.0 * self.along_track_sigma_m),
            label: format!(
                "Moving pressure disturbance ({:.0} Pa, {:.1} m/s, Proudman ratio {:.2})",
                self.peak_pressure_pa,
                self.speed_m_s,
                self.proudman_ratio(),
            ),
            recurrence_note: None,
            camera_view: None,
            source_geometry: None,
            meteotsunami_forcing: Some(*self),
        }
    }

    /// Atmospheric pressure and local Cartesian gradient at an east/north
    /// offset from the t=0 source centre.
    pub fn pressure_and_gradient(&self, east_m: f64, north_m: f64, time_s: f64) -> (f64, f64, f64) {
        let travelled_m = self.speed_m_s * time_s.max(0.0);
        if travelled_m > self.track_length_m {
            return (0.0, 0.0, 0.0);
        }
        let heading = self.heading_deg.to_radians();
        let along = east_m * heading.sin() + north_m * heading.cos() - travelled_m;
        let across = east_m * heading.cos() - north_m * heading.sin();
        let along_var = self.along_track_sigma_m * self.along_track_sigma_m;
        let cross_var = self.cross_track_sigma_m * self.cross_track_sigma_m;
        if along_var <= 0.0 || cross_var <= 0.0 {
            return (0.0, 0.0, 0.0);
        }
        let pressure = self.peak_pressure_pa
            * (-0.5 * (along * along / along_var + across * across / cross_var)).exp();
        let dp_dalong = -pressure * along / along_var;
        let dp_dacross = -pressure * across / cross_var;
        let dp_deast = dp_dalong * heading.sin() + dp_dacross * heading.cos();
        let dp_dnorth = dp_dalong * heading.cos() - dp_dacross * heading.sin();
        (pressure, dp_deast, dp_dnorth)
    }

    /// Apply one explicit pressure-gradient source increment. Calling this at
    /// the step midpoint gives second-order timing for the prescribed source
    /// while the hydrodynamic update remains the solver's existing scheme.
    #[cfg(not(feature = "browser-wasm"))]
    pub fn apply_pressure_gradient(&self, grid: &mut SwGrid, time_s: f64, dt_s: f64) {
        if dt_s == 0.0 || !dt_s.is_finite() {
            return;
        }
        for row in 0..grid.ny {
            let lat = grid.south_lat + (row as f64 + 0.5) * grid.dlat_deg;
            let north_m = (lat - self.location.lat_deg).to_radians() * super::constants::R_EARTH_M;
            for column in 0..grid.nx {
                let index = row * grid.nx + column;
                if grid.h_m[index] + grid.eta_m[index] <= super::solver::WET_DEPTH_EPSILON_M {
                    continue;
                }
                let lon = grid.west_lon + (column as f64 + 0.5) * grid.dlon_deg;
                let delta_lon = (lon - self.location.lon_deg + 540.0).rem_euclid(360.0) - 180.0;
                let mean_lat = 0.5 * (lat + self.location.lat_deg);
                let east_m = delta_lon.to_radians()
                    * super::constants::R_EARTH_M
                    * mean_lat.to_radians().cos();
                let (_, dp_deast, dp_dnorth) = self.pressure_and_gradient(east_m, north_m, time_s);
                grid.u_ms[index] -= dt_s * dp_deast / RHO_SEAWATER;
                grid.v_ms[index] -= dt_s * dp_dnorth / RHO_SEAWATER;
            }
        }
    }
}

#[cfg(all(test, not(feature = "browser-wasm")))]
mod tests {
    use super::*;

    fn source() -> MeteotsunamiSource {
        MeteotsunamiSource {
            peak_pressure_pa: 300.0,
            speed_m_s: 30.0,
            heading_deg: 90.0,
            along_track_sigma_m: 20_000.0,
            cross_track_sigma_m: 40_000.0,
            track_length_m: 300_000.0,
            water_depth_m: 100.0,
            location: GeoPoint {
                lat_deg: 0.0,
                lon_deg: 0.0,
                depth_m: 100.0,
            },
        }
    }

    #[test]
    fn pressure_gradient_points_away_from_positive_pressure_peak() {
        let (_, east_gradient, north_gradient) = source().pressure_and_gradient(10_000.0, 0.0, 0.0);
        assert!(east_gradient < 0.0);
        assert!(north_gradient.abs() < 1.0e-12);
    }

    #[test]
    fn source_switches_off_after_finite_track() {
        let s = source();
        assert_eq!(
            s.pressure_and_gradient(0.0, 0.0, s.track_length_m / s.speed_m_s + 1.0),
            (0.0, 0.0, 0.0),
        );
    }

    #[test]
    fn pressure_source_changes_velocity_without_injecting_eta() {
        let mut grid = SwGrid::new(-0.2, -0.2, 0.2, 0.2, 0.05, 0.05);
        grid.fill_uniform_depth(100.0);
        let eta_before = grid.eta_m.clone();
        source().apply_pressure_gradient(&mut grid, 0.0, 10.0);
        assert_eq!(grid.eta_m, eta_before);
        assert!(grid.u_ms.iter().any(|value| value.abs() > 0.0));
    }
}
