//! Nuclear-detonation tsunami source physics.
//!
//! References:
//! - Glasstone, S., & Dolan, P. J. (1977). *The Effects of Nuclear Weapons*
//!   (3rd ed.). U.S. Department of Defense / DOE. Chapter 6 (underwater).
//! - Le Méhauté, B., & Wang, S. (1996). *Water Waves Generated by Underwater
//!   Explosion*. World Scientific.
//! - Van Dorn, W. G., Le Méhauté, B., & Hwang, L.-S. (1968). Handbook of
//!   explosion-generated water waves. Tetra Tech.
//! - Defense Nuclear Agency (1996). DNA-TR-96-77: Underwater nuclear explosion
//!   wave-generation efficiency study. (Reports ~5% energy → wave action.)
//!
//! Underwater nuclear explosions create a bubble cavity that pulses, then
//! collapses to form a propagating surface wave. Wave-generation efficiency
//! is very low — ~5% of yield energy — and the wave radiates in 360°, so the
//! per-direction energy is even lower. This is why even multi-megaton tests
//! produced modest waves, and why the Russian "Poseidon 500-m tsunami" claim
//! is regarded by Western analysts (Hambling 2022; Spriggs LLNL) as
//! propaganda.

use serde::{Deserialize, Serialize};

use super::constants::{G_EARTH, J_PER_KT_TNT, NUCLEAR_WAVE_EFFICIENCY, RHO_SEAWATER};
use super::{GeoPoint, InitialDisplacement};

#[derive(Debug, Clone, Copy, Serialize, Deserialize, PartialEq, Eq)]
pub enum BurstMode {
    /// Surface burst on water — Crossroads-Able geometry.
    Surface,
    /// Shallow underwater burst, depth < cavity radius — Crossroads-Baker.
    Shallow,
    /// Deep underwater burst at "optimum" depth maximizing wave generation
    /// (~0.4 × cavity radius per Le Méhauté & Wang 1996).
    DeepOptimal,
    /// Very deep — depth ≫ cavity radius; most energy stays trapped.
    Abyssal,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct NuclearBurst {
    /// Total weapon yield, kilotons of TNT.
    pub yield_kt: f64,
    /// Burst geometry.
    pub burst_mode: BurstMode,
    /// Depth of burst below the sea surface, meters (0 for surface).
    pub burst_depth_m: f64,
    /// Water depth at the detonation point, meters.
    pub water_depth_m: f64,
    /// Surface coordinates.
    pub location: GeoPoint,
}

impl NuclearBurst {
    /// Total energy in joules.
    pub fn energy_j(&self) -> f64 {
        self.yield_kt * J_PER_KT_TNT
    }

    /// Energy in megatons of TNT (convenience).
    pub fn yield_mt(&self) -> f64 {
        self.yield_kt / 1000.0
    }

    /// Maximum bubble / cavity radius from a deep underwater explosion, meters.
    ///
    /// Glasstone & Dolan 1977 §6.66 give the Snay scaling for maximum bubble
    /// radius from a deep underwater burst:
    ///
    /// ```text
    /// R_max (m) ≈ 13.6 · (W_kt)^(1/3) · (ρ_ref / ρ_local)^(1/3) · (p_ref / p_h)^(1/3)
    /// ```
    ///
    /// where `p_h` is hydrostatic pressure at burst depth and `p_ref` = 1 atm.
    /// For a near-surface burst (depth ~0) the cavity is "vented" and the
    /// effective radius is approximated by the Le Méhauté & Wang 1996 scaling.
    pub fn cavity_radius_m(&self) -> f64 {
        let w_kt = self.yield_kt.max(0.0);
        // Hydrostatic pressure at/above the surface can never drop below 1 atm,
        // so floor it: a (mis-entered) negative burst depth would otherwise make
        // p_h_atm ≤ 0 → division by zero (+inf radius) or a cube-root of a
        // negative number (NaN radius), poisoning the amplitude path.
        let p_h_atm = (1.0 + self.burst_depth_m / 10.0).max(1.0); // each 10 m water ≈ 1 atm
        let base = 13.6 * w_kt.powf(1.0 / 3.0) / p_h_atm.powf(1.0 / 3.0);
        match self.burst_mode {
            BurstMode::Surface => 0.5 * base,
            BurstMode::Shallow => 0.8 * base,
            BurstMode::DeepOptimal => base,
            BurstMode::Abyssal => 0.6 * base, // overburdened cavity
        }
    }

    /// Effective energy delivered to propagating waves, joules.
    /// Per DNA 1996, ≈ 5% of the yield ends up in wave action; the rest is
    /// thermal radiation, shock-wave dissipation, vaporization, and turbulence.
    /// Surface bursts are even less efficient.
    pub fn wave_energy_j(&self) -> f64 {
        let efficiency_scale = match self.burst_mode {
            BurstMode::Surface => 0.4,
            BurstMode::Shallow => 0.8,
            BurstMode::DeepOptimal => 1.0,
            BurstMode::Abyssal => 0.5,
        };
        self.energy_j() * NUCLEAR_WAVE_EFFICIENCY * efficiency_scale
    }

    /// Peak initial wave amplitude at the cavity rim, meters.
    ///
    /// From the energy balance: half of the wave energy goes to potential
    /// energy of the rim wave, which has volume ≈ π R_c² · A and density ρ_w.
    /// Therefore:
    ///
    /// ```text
    /// A ≈ sqrt( E_w / (π ρ_w g R_c²) )
    /// ```
    ///
    /// (Le Méhauté & Wang 1996 closed-form for a stationary cavity.)
    ///
    /// The energy-balance form goes unbounded with yield because energy
    /// scales linearly with W but R_c only as W^(1/3.4). At multi-megaton
    /// yields the geometric upper bound on amplitude becomes the cavity
    /// radius itself — physically you can't have a rim wave taller than the
    /// cavity is deep. We clamp at `0.5 · R_c`, consistent with the Wang
    /// 1996 empirical upper envelope from Crossroads-Baker-class data.
    pub fn initial_amplitude_m(&self) -> f64 {
        let r_c = self.cavity_radius_m();
        let e_w = self.wave_energy_j();
        let energy_balance =
            (e_w / (std::f64::consts::PI * RHO_SEAWATER * G_EARTH * r_c.powi(2))).sqrt();
        let geometric_cap = 0.5 * r_c;
        energy_balance.min(geometric_cap)
    }

    /// Equivalent seismic moment magnitude (very approximate). Nuclear tests
    /// have well-documented Mw — e.g., 50-Mt Tsar Bomba registered ~Mw 5.0–5.25.
    /// We use 1% coupling efficiency to ground motion (Glasstone & Dolan §6.92).
    pub fn seismic_mw_equivalent(&self) -> f64 {
        let radiated_j = 0.01 * self.energy_j();
        super::mw_from_radiated_j(radiated_j)
    }

    pub fn initial_displacement(&self) -> InitialDisplacement {
        let r_c = self.cavity_radius_m();
        let center = GeoPoint {
            depth_m: self.water_depth_m,
            ..self.location
        };
        InitialDisplacement {
            center,
            cavity_radius_m: r_c,
            peak_amplitude_m: self.initial_amplitude_m(),
            source_energy_j: self.energy_j(),
            seismic_mw_equivalent: self.seismic_mw_equivalent(),
            dominant_wavelength_m: Some(2.0 * r_c),
            label: format!(
                "{:.1} Mt {:?} burst at {:.0} m depth",
                self.yield_mt(),
                self.burst_mode,
                self.burst_depth_m
            ),
            recurrence_note: None,
            camera_view: None,
        }
    }
}

/// Nuclear-explosion far-field amplitude attenuation.
///
/// Unlike an asteroid impact (Ward–Asphaug `r^-5/6`), the nuclear cavity
/// produces a comparatively short wavelength that dispersively spreads as
/// `r^-1` plus geometric spreading on a 2-D ocean surface. Le Méhauté & Wang
/// 1996 give an empirical fit `A(r) ≈ A_0 · (R_c / r)` for `r ≫ R_c`.
pub fn far_field_amplitude_m(initial_amplitude_m: f64, cavity_radius_m: f64, range_m: f64) -> f64 {
    if range_m <= cavity_radius_m {
        return initial_amplitude_m;
    }
    initial_amplitude_m * (cavity_radius_m / range_m)
}

/// Convenience for the canonical "Russia Poseidon" propaganda yield.
/// Russian state TV (Kiselyov, May 2022) claimed a 100-Mt warhead capable of
/// a 500-m tsunami. Western technical analyses (Hambling 2022; Spriggs LLNL)
/// regard this as unrealistic by 1–2 orders of magnitude.
pub fn poseidon_propaganda(location: GeoPoint, water_depth_m: f64) -> NuclearBurst {
    NuclearBurst {
        yield_kt: 100_000.0, // 100 Mt
        burst_mode: BurstMode::DeepOptimal,
        burst_depth_m: 100.0,
        water_depth_m,
        location,
    }
}

/// Conservative realistic Poseidon yield (Hambling 2022; ~few-MT estimate).
pub fn poseidon_realistic(location: GeoPoint, water_depth_m: f64) -> NuclearBurst {
    NuclearBurst {
        yield_kt: 2_000.0, // 2 Mt
        burst_mode: BurstMode::DeepOptimal,
        burst_depth_m: 100.0,
        water_depth_m,
        location,
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    /// Tsar Bomba (50 Mt airburst) hypothetically detonated at deep-optimal
    /// underwater depth should produce a wave on the order of meters at km
    /// distance — definitively *not* a hundreds-of-meters tsunami.
    #[test]
    fn tsar_bomba_underwater_modest() {
        let burst = NuclearBurst {
            yield_kt: 50_000.0,
            burst_mode: BurstMode::DeepOptimal,
            burst_depth_m: 200.0,
            water_depth_m: 4_000.0,
            location: GeoPoint {
                lat_deg: 73.0,
                lon_deg: 55.0,
                depth_m: 4_000.0,
            },
        };
        let d = burst.initial_displacement();
        // Initial cavity amplitude can be tens of meters near the source...
        assert!(d.peak_amplitude_m > 1.0 && d.peak_amplitude_m < 500.0);
        // ...but at 100 km it should be a few meters at most.
        let a_100km = far_field_amplitude_m(d.peak_amplitude_m, d.cavity_radius_m, 100_000.0);
        assert!(
            a_100km < 20.0,
            "Tsar Bomba @ 100 km gave {} m — propaganda-level, formula broken",
            a_100km
        );
    }

    /// Poseidon propaganda yield should produce a wave that is *clearly* much
    /// smaller than 500 m at 100 km — the entire point of comparing it.
    #[test]
    fn poseidon_propaganda_is_not_500m() {
        let burst = poseidon_propaganda(
            GeoPoint {
                lat_deg: 50.0,
                lon_deg: -10.0,
                depth_m: 4_000.0,
            },
            4_000.0,
        );
        let d = burst.initial_displacement();
        let a_100km = far_field_amplitude_m(d.peak_amplitude_m, d.cavity_radius_m, 100_000.0);
        assert!(
            a_100km < 50.0,
            "Even 100 Mt should not produce >50 m at 100 km; got {}",
            a_100km
        );
    }
}
