//! Volcanic caldera- and flank-collapse tsunami source physics.
//!
//! A collapse is represented as a finite elliptical Gaussian displacement.
//! The footprint axes are one-sigma lengths, so the coupled volume and the
//! peak displacement remain auditable: `V = 2π σx σy |η₀|`.  Caldera collapse
//! produces initial subsidence (negative `η₀`); a water-coupled flank collapse
//! produces an initial positive displacement.  A finite-duration coupling
//! factor reduces the instantaneous source when the collapse is slow compared
//! with the local long-wave crossing time.
//!
//! This is a source parameterisation, not a volcanic forecast or a substitute
//! for multiphase, dispersive, or non-hydrostatic near-field modelling.
//!
//! References:
//! - Paris, R. (2024), "A Review of Tsunamis Generated by Volcanoes",
//!   *Pure and Applied Geophysics*, doi:10.1007/s00024-024-03515-y.
//! - Zaniboni et al. (2026), *Natural Hazards and Earth System Sciences*
//!   26, 631–649, doi:10.5194/nhess-26-631-2026.

use serde::{Deserialize, Serialize};

use super::constants::{G_EARTH, RHO_SEAWATER};
use super::{GeoPoint, InitialDisplacement, InitialSourceGeometry};

#[derive(Debug, Clone, Copy, Serialize, Deserialize, PartialEq, Eq)]
pub enum VolcanicCollapseKind {
    Caldera,
    FlankCollapse,
}

#[derive(Debug, Clone, Copy, Serialize, Deserialize)]
pub struct VolcanicCollapseSource {
    pub kind: VolcanicCollapseKind,
    /// Collapsing or water-coupled volume, m³.
    pub volume_m3: f64,
    /// One-sigma source footprint length, metres.
    pub footprint_length_m: f64,
    /// One-sigma source footprint width, metres.
    pub footprint_width_m: f64,
    /// Collapse duration, seconds. Longer durations couple less efficiently
    /// to the initial long wave in this depth-averaged approximation.
    pub collapse_duration_s: f64,
    /// Fraction of the collapse volume that couples to the water column.
    pub coupling_fraction: f64,
    /// Representative water depth at the source, metres.
    pub water_depth_m: f64,
    pub location: GeoPoint,
}

impl VolcanicCollapseSource {
    pub fn coupled_volume_m3(&self) -> f64 {
        self.volume_m3 * self.coupling_fraction
    }

    pub fn footprint_area_m2(&self) -> f64 {
        2.0 * std::f64::consts::PI * self.footprint_length_m * self.footprint_width_m
    }

    /// Long-wave time across the geometric-mean one-sigma footprint.
    pub fn long_wave_crossing_time_s(&self) -> f64 {
        let characteristic_length =
            (self.footprint_length_m * self.footprint_width_m).sqrt();
        let celerity = (G_EARTH * self.water_depth_m.max(1.0)).sqrt();
        characteristic_length / celerity
    }

    /// Smooth finite-duration reduction based on the source-time / wave-time
    /// ratio. The floor avoids a numerically vanishing initial field while
    /// preserving the intended ordering between rapid and slow collapse.
    pub fn finite_time_coupling(&self) -> f64 {
        let ratio = self.collapse_duration_s.max(0.0) / self.long_wave_crossing_time_s().max(1.0);
        (1.0 / (1.0 + ratio * ratio).sqrt()).clamp(0.05, 1.0)
    }

    /// Signed peak surface displacement. Caldera subsidence is negative;
    /// flank collapse is positive in the water-coupled source convention.
    pub fn signed_peak_amplitude_m(&self) -> f64 {
        let static_amplitude = self.coupled_volume_m3() / self.footprint_area_m2();
        let sign = match self.kind {
            VolcanicCollapseKind::Caldera => -1.0,
            VolcanicCollapseKind::FlankCollapse => 1.0,
        };
        sign * static_amplitude * self.finite_time_coupling()
    }

    pub fn initial_displacement(&self) -> InitialDisplacement {
        let signed_amplitude = self.signed_peak_amplitude_m();
        let footprint_radius_m =
            (self.footprint_length_m * self.footprint_width_m).sqrt();
        let source_area_m2 = self.footprint_area_m2();
        let source_energy_j =
            0.5 * RHO_SEAWATER * G_EARTH * signed_amplitude * signed_amplitude * source_area_m2;
        let kind_label = match self.kind {
            VolcanicCollapseKind::Caldera => "caldera subsidence",
            VolcanicCollapseKind::FlankCollapse => "flank-collapse uplift",
        };
        let center = GeoPoint {
            depth_m: self.water_depth_m,
            ..self.location
        };
        InitialDisplacement {
            center,
            cavity_radius_m: footprint_radius_m,
            peak_amplitude_m: signed_amplitude.abs(),
            source_energy_j,
            seismic_mw_equivalent: super::mw_from_radiated_j(source_energy_j),
            dominant_wavelength_m: Some(2.0 * footprint_radius_m),
            label: format!(
                "Volcanic {kind_label} ({:.2}×10⁹ m³, {:.0} s collapse)",
                self.volume_m3 / 1.0e9,
                self.collapse_duration_s
            ),
            recurrence_note: None,
            camera_view: None,
            source_geometry: Some(InitialSourceGeometry::VolcanicCollapse {
                collapse_kind: self.kind,
                footprint_length_m: self.footprint_length_m,
                footprint_width_m: self.footprint_width_m,
                collapse_duration_s: self.collapse_duration_s,
                signed_peak_amplitude_m: signed_amplitude,
            }),
            meteotsunami_forcing: None,
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn source(kind: VolcanicCollapseKind, duration_s: f64) -> VolcanicCollapseSource {
        VolcanicCollapseSource {
            kind,
            volume_m3: 1.0e9,
            footprint_length_m: 2_000.0,
            footprint_width_m: 1_000.0,
            collapse_duration_s: duration_s,
            coupling_fraction: 0.25,
            water_depth_m: 500.0,
            location: GeoPoint {
                lat_deg: 0.0,
                lon_deg: 0.0,
                depth_m: 500.0,
            },
        }
    }

    #[test]
    fn collapse_kind_sets_initial_displacement_sign() {
        assert!(source(VolcanicCollapseKind::Caldera, 10.0).signed_peak_amplitude_m() < 0.0);
        assert!(source(VolcanicCollapseKind::FlankCollapse, 10.0).signed_peak_amplitude_m() > 0.0);
    }

    #[test]
    fn slower_collapse_has_weaker_instantaneous_source() {
        let fast = source(VolcanicCollapseKind::FlankCollapse, 1.0).signed_peak_amplitude_m();
        let slow = source(VolcanicCollapseKind::FlankCollapse, 3_600.0).signed_peak_amplitude_m();
        assert!(fast > slow);
        assert!(slow > 0.0);
    }

    #[test]
    fn initial_displacement_has_finite_geometry_and_energy() {
        let initial = source(VolcanicCollapseKind::Caldera, 60.0).initial_displacement();
        assert!(initial.peak_amplitude_m.is_finite());
        assert!(initial.source_energy_j.is_finite());
        assert!(initial.cavity_radius_m > 0.0);
        assert!(matches!(
            initial.source_geometry,
            Some(InitialSourceGeometry::VolcanicCollapse {
                signed_peak_amplitude_m,
                ..
            }) if signed_peak_amplitude_m < 0.0
        ));
    }
}
