import crypto from "node:crypto";
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const dist = path.join(root, "dist");

function walk(directory) {
  return fs.readdirSync(directory, { withFileTypes: true }).flatMap((entry) => {
    const absolute = path.join(directory, entry.name);
    return entry.isDirectory() ? walk(absolute) : [absolute];
  });
}

if (!fs.existsSync(path.join(dist, "index.html"))) {
  throw new Error("dist/index.html is missing; run the Vite production build before generating the PWA worker.");
}

const files = walk(dist)
  .filter((file) => path.basename(file) !== "sw.js" && !file.endsWith(".map"))
  .sort((left, right) => left.localeCompare(right));
const urls = files.map((file) => `/${path.relative(dist, file).replaceAll(path.sep, "/")}`);
const digest = crypto.createHash("sha256");
for (const file of files) {
  digest.update(path.relative(dist, file));
  digest.update(fs.readFileSync(file));
}
const cacheName = `cataclysm-offline-${digest.digest("hex").slice(0, 16)}`;
const worker = `// Generated by scripts/build-pwa.mjs. Do not edit dist/sw.js directly.
const CACHE_NAME = ${JSON.stringify(cacheName)};
const PRECACHE_URLS = ${JSON.stringify(urls, null, 2)};

self.addEventListener("install", (event) => {
  event.waitUntil(caches.open(CACHE_NAME).then((cache) => cache.addAll(PRECACHE_URLS)).then(() => self.skipWaiting()));
});

self.addEventListener("activate", (event) => {
  event.waitUntil(
    caches.keys()
      .then((keys) => Promise.all(keys.filter((key) => key.startsWith("cataclysm-offline-") && key !== CACHE_NAME).map((key) => caches.delete(key))))
      .then(() => self.clients.claim()),
  );
});

self.addEventListener("fetch", (event) => {
  if (event.request.method !== "GET") return;
  const url = new URL(event.request.url);
  if (url.origin !== self.location.origin) return;
  event.respondWith(
    caches.match(url.pathname, { ignoreVary: true }).then((cached) => cached ?? fetch(event.request).catch(() => {
      if (event.request.mode === "navigate") return caches.match("/index.html", { ignoreVary: true });
      return Response.error();
    })),
  );
});
`;
fs.writeFileSync(path.join(dist, "sw.js"), worker);
const totalBytes = files.reduce((sum, file) => sum + fs.statSync(file).size, 0);
console.log(`PWA offline cache ${cacheName}: ${urls.length} files, ${(totalBytes / 1_048_576).toFixed(1)} MiB.`);
